language: csharp
mono:
  - 3.12.0

install:
# innosetup
 - sudo add-apt-repository -y ppa:ubuntu-wine/ppa
 - sudo apt-get update
 - sudo apt-get install wine1.7
 - sudo apt-get clean

script:
 - xbuild /p:Configuration=Release ManicDigger.sln
 - ./build.sh
 - echo `date +%Y-%m-%d` > output/version.txt
 - mv output ManicDiggerBinary
 - zip -r -9 ManicDiggerBinary.zip ManicDiggerBinary
# innosetup
 - mv ManicDiggerBinary output
 - wget http://constexpr.org/innoextract/files/innoextract-1.4-windows-r2.zip
# release pinned to 5.5.5 due to innoextract compatibility issues
# - wget http://www.jrsoftware.org/download.php/is-unicode.exe
 - wget http://files.jrsoftware.org/is/5/isetup-5.5.5-unicode.exe
 - mv isetup-5.5.5-unicode.exe is-unicode.exe
 - unzip innoextract-1.4-windows-r2.zip
 - wine innoextract-1.4-windows-r2/innoextract.exe is-unicode.exe
 - wine app/ISCC.exe setup.iss
 - mv output2/setup.exe ManicDiggerSetup.exe
# deploy builds
 - ./extra/travis_deploy_ghpages.sh

env:
  global:
  - GH_REF: github.com/manicdigger/manicdigger-builds
  - secure: 0+XB4Y76gJ4kzJkbGNjsPHAT1zYLhJb4T5w8MWeOa8SQcla+6E5a2gtE/tMQSXMJHtmA+jDUJho5VJ8yRpIVwnnGVYOxzmAdEulrSk9dQaYs9YNSoE7qfxMkomffXyKTOsWdu75c5/iMxI0iqBg5IKm/lBB5BBDqMGWSrfW+3hk=

deploy:
  provider: releases
  api_key:
    secure: nCSaKiJTAiONcbbZ3/PJ3IhDd4VMhI8DNvnoX5zxUI3nJ2Y1BonoCdkmRy4y0mXr6UHS/apNY6yGl2oSEZotp2GjmH88obBE4D83JL+mQmrDY/eIy6963/Hp+615p6nOXm8K/wxX3NVRr1dPKGV5v9bRu6GF+UsPT7piMOBWqpo=
  file:
    - out/ManicDigger`date +%Y-%m-%d`Binary.zip
    - out/ManicDigger`date +%Y-%m-%d`Setup.exe
  skip_cleanup: true
  on:
    tags: true
    repo: manicdigger/manicdigger
